const StudentActionTypes = {
    FETCH_SINGLE_STUDENT: 'FETCH_SINGLE_STUDENT',
    FETCH_ALL_STUDENTS: 'FETCH_ALL_STUDENTS',
    DELETE_STUDENT: 'DELETE_STUDENT',
    CREATE_STUDENT: 'CREATE_STUDENT',
    UPDATE_STUDENT: 'UPDATE_STUDENT'
}

export default StudentActionTypes;