const CampusActionTypes = {
    FETCH_SINGLE_CAMPUS: 'FETCH_SINGLE_CAMPUS',
    FETCH_ALL_CAMPUSES: 'FETCH_ALL_CAMPUSES',
    DELETE_CAMPUS: 'DELETE_CAMPUS',
    CREATE_CAMPUS: 'CREATE_CAMPUS',
    UPDATE_CAMPUS: 'UPDATE_CAMPUS'
}

export default CampusActionTypes;